#pragma once
#include "CoreMinimal.h"
#include "EAudioVOType.generated.h"

UENUM(BlueprintType)
namespace EAudioVOType {
    enum Type {
        None,
        FollowMe,
        Forward,
        Retreat,
        Confusion,
        Disappointment,
        HoldGround,
        Panic,
        Incoming,
        BehindUs,
        Awe,
        BattlecryStanding,
        BattlecrySprinting,
        BattlecryCrouching,
        Yes,
        No,
        Help,
        Maybe,
        Thanks,
        Welcome,
        Sorry,
        Taunt,
        Laugh,
        RespectAlly,
        RespectEnemy,
        PersonalPersonalityOption1,
        PersonalPersonalityOption2,
        TacticalPersonalityOption1,
        TacticalPersonalityOption2,
        EmotePersonalityOption1,
        EmotePersonalityOption2,
        RequestHelp,
        RequestDeath,
        RefuseDeath,
        AcceptDeath,
        Cheer,
        Goodbye,
        Hello,
        BegCower,
        Soliloquy,
        Customization,
        Friendly,
        Enemy,
        Cry,
        Cower,
        IdleChatter,
        LetMeIn,
        Pain,
        DeathCry,
        DefendMe,
        Hymn,
        Chant,
        YouAreWelcome,
        Prayer,
        Rally,
        RequestHeal,
        AncientCurse,
        AnimalKinship,
        MAX,
    };
}

