#pragma once
#include "CoreMinimal.h"
#include "EAudioAutoVOType.generated.h"

UENUM(BlueprintType)
namespace EAudioAutoVOType {
    enum Type {
        None,
        Crippled,
        DeathArm,
        DeathGen,
        DeathLeg,
        HorseAccelerate,
        HorseControl,
        HorseDeath,
        HorseDecelerate,
        HorseMount,
        HorseSoothe,
        Invalid,
        Negative,
        NoAmmo,
        Pain,
        Positive,
        Rage,
        Revived,
        Reviving,
        Sorry,
        Thanks,
        RefuseDeath,
        KillArchers,
        Defend,
        DefendWinning,
        HoldWalls,
        AttackWinning,
        Attack,
        GateAttack,
        CavalryIncomingEnemy,
        CavalryWarning,
        CavalryCharge,
        SiegeDefend,
        SiegeDestroy,
        CavalryIncomingAlly,
        GateLost,
        GateWon,
        GateDefend,
        SiegeRam,
        ObjKill,
        ObjBurn,
        SiegeRamStop,
        ObjPeasantDefend,
        ObjPeasantKill,
        SiegeTower,
        ObjLordDefend,
        ObjLordKill,
        SiegeTowerStop,
        SiegeFire,
        ObjSupplySteal,
        OffenseCharge,
        DefenseShields,
        ObjSupplyDefend,
        OffenseFire,
        DefensePrepare,
        MAX,
    };
}

