#pragma once
#include "CoreMinimal.h"
#include "EInventoryType.generated.h"

UENUM(BlueprintType)
enum class EInventoryType : uint8 {
    None,
    Axe,
    Ballista,
    BandageKit,
    BastardSword,
    BattleAxe,
    Bow,
    Catapult,
    Crossbow,
    Cudgel,
    Dagger,
    DaneAxe,
    Greatsword,
    Goedendag,
    Halberd,
    HeavyCavalrySword,
    HeavyMace,
    HeavyShield,
    Horse,
    Fists,
    Katars,
    Lance,
    LightShield,
    Mace,
    Maul,
    MediumShield,
    Messer,
    PoleAxe,
    PoleHammer,
    Quarterstaff,
    ShortSword,
    Spear,
    Sword,
    ThrowingAxe,
    ThrowingKnife,
    WarHammer,
    Javelin,
    Absurd,
    BatteringRam,
    TopplingStone,
    Bombard,
    MAX,
};

