#pragma once
#include "CoreMinimal.h"
#include "EWeaponTag.generated.h"

UENUM(BlueprintType)
enum class EWeaponTag : uint8 {
    None,
    Axe,
    BastardSword,
    BattleAxe,
    Cudgel,
    Dagger,
    DaneAxe,
    Greatsword,
    Halberd,
    HeavyMace,
    Lance,
    Mace,
    Maul,
    Messer,
    PoleAxe,
    PoleHammer,
    ShortSword,
    Spear,
    Sword,
    WarHammer,
    Bow,
    Crossbow,
    ThrowingAxe,
    ThrowingKnife,
    HeavyShield,
    LightShield,
    MediumShield,
    Javelin,
    Falchion,
    Shovel,
    SledgeHammer,
    PickAxe,
    TwoHandedHammer,
    WarClub,
    ExecutionersAxe,
    Glaive,
    Knife,
    WarAxe,
    MorningStar,
    Hatchet,
    OneHandedSpear,
    ThrowingMallet,
    Rapier,
    HighlandSword,
    WarBow,
    HeavyCrossbow,
    Katars,
    Quarterstaff,
    HeavyCavalrySword,
    Goedendag,
    ArmouredFists,
    MAX,
};

